- name: firewalld allow 80 port
  firewalld: permanent=True service=http state=enabled immediate=true

- name: installation from yum
  yum: name="{{item}}" state=installed
  with_items:
    - httpd

- name: service start
  service: name=httpd state=started enabled=yes

- name: copy index.html
  copy:
    src=files/index.html
    dest=/var/www/html/index.html

- name: copy index.html
  copy:
    src=files/373-pictogram-free.jpg
    dest=/var/www/html/373-pictogram-free.jpg

#- name: copy submit.cgi
#  copy:
#    src=files/submit.cgi
#    dest=/var/www/cgi-bin/submit.cgi
