- name: mariadb（mysql） install
  yum: name="{{item}}" state=latest
  with_items:
    - mariadb
    - mariadb-server
    - mysql-devel

- name: mariadb start
  service: name=mariadb state=started enabled=yes

- name: firewalld mariadb(mysql) allow DB port
  firewalld: permanent=True service=mysql state=enabled immediate=true

- name: set root user
  mysql_user:
    name: root
    host: localhost
    password: ogiman

- name: createdb
  mysql_db:
    name: ogimandb
    state: present

- name: createtable
  shell: mysql -u root -p ogiman -h localhost $ogimandb -e "create table ogimantable (id int not null auto_increment,date datetime,name varchar(20),feel varchar(20),PRIMARY KEY(id) );"
